openapi: 3.0.0
servers:
  - description: APIHub API Auto Mocking Scheduling and Listing court-schedule
    url: https://virtserver.swaggerhub.com/HMCTS-DTS/api-cp-crime-schedulingandlisting-courtschedule/0.0.0

info:
  description: Scheduling and Listing API providing the court schedule
  version: 0.0.0
  title: Scheduling and Listing Court Schedule API
  contact:
    email: no-reply@hmcts.net
  license:
    name: MIT
    url: 'https://opensource.org/licenses/MIT'

paths:
  /case/{case_urn}/courtschedule:
    get:
      description: Retrieve details of a court schedule by case URN.
      operationId: getCourtScheduleByCaseUrn
      tags:
        - court Schedule
      parameters:
        - in: path
          name: case_urn
          required: true
          description: Unique reference number for the case
          schema:
            type: string

      responses:
        '200':
          description:  case found

          content:
            application/json:
              schema:
                $ref: "courtSchedule.schema.json"
              example:
                courtSchedule:
                  - hearings:
                      - hearingId: HRG-123456
                        hearingType: Trial
                        hearingDescription: Sentencing for theft case
                        listNote: Requires interpreter
                        courtSittings:
                          - sittingStart: 2025-03-25T09:00:00Z
                            sittingEnd: 2025-03-25T12:00:00Z
                            judiciaryid: 123e4567-e89b-12d3-a456-426614174000
                            courtHouse: 223e4567-e89b-12d3-a456-426614174111

        '400':
          description: bad input parameter