openapi: 3.0.0
servers:
  - description: APIHub API Auto Mocking Scheduling and Listing court-schedule
    url: https://virtserver.swaggerhub.com/HMCTS-DTS/api-cp-crime-schedulingandlisting-courtschedule/0.0.0

info:
  title: Common Platform API Scheduling and Listing Court Schedule
  description: Scheduling and Listing API providing the court schedule
  version: 0.0.0
  contact:
    email: no-reply@hmcts.com
  license:
    name: MIT
    url: 'https://opensource.org/licenses/MIT'

paths:
  /case/{case_urn}/courtschedule:
    get:
      description: Retrieve details of a court schedule by case URN.
      operationId: getCourtScheduleByCaseUrn
      tags:
        - court Schedule
      parameters:
        - in: path
          name: case_urn
          required: true
          description: Unique reference number for the case
          schema:
            type: string

      responses:
        '200':
          description:  case found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CourtScheduleResponse"
        '400':
          description: bad input parameter

components:
  schemas:
    CourtScheduleResponse:
      type: object
      properties:
        courtSchedule:
          type: array
          items:
            type: object
            properties:
              hearings:
                type: array
                items:
                  type: object
                  description: Hearing details of the case and associated details for the sitting
                  properties:
                    hearingId:
                      description: Id of the hearing associated with the scheduling system
                      type: string
                      example: "HRG-123456"
                    hearingType:
                      description: Type of hearing being presented
                      type: string
                      example: "Preliminary"
                    hearingDescription:
                      description: Description associated to the hearing
                      type: string
                      example: "Initial appearance for case 456789"
                    listNote:
                      description: Will always be required but can be null
                      type: string
                      example: "Judge prefers afternoon start"
                    courtSittings:
                      description: Details of court sittings
                      type: array
                      items:
                        type: object
                        properties:
                          sittingStart:
                            description: Sitting Start Time
                            type: string
                            format: date-time
                            example: "2025-03-25T09:00:00Z"
                          sittingEnd:
                            description: Sitting End Time
                            type: string
                            format: date-time
                            example: "2025-03-25T12:00:00Z"
                          judiciaryId:
                            description: Judge ref id
                            type: string
                            pattern: "[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}$"
                            example: "123e4567-e89b-12d3-a456-426614174000"
                          courtHouse:
                            description: Court house details ref id
                            type: string
                            pattern: "[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}$"
                            example: "223e4567-e89b-12d3-a456-426614174111"