name: Linting of OpenAPI documents on Pull Requests

on:
  pull_request:
    branches:
      - master
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      # Run Spectral
      - uses: stoplightio/spectral-action@latest
        with:
          file_glob: openapi/**/*.yml
